Documentation: passing arguments in interactive environments
DLR-RM/rl-baselines3-zoo pull request #298
Opened 2022-10-12 12:25 UTC by richter43

Addition of instructions and an example for executing the training/enjoy framework in an interactive computing platform.

## Description
Modified README.md

## Motivation and Context

- [x] I have raised an issue to propose this change ([required](https://github.com/DLR-RM/stable-baselines3/blob/master/CONTRIBUTING.md) for new features and bug fixes)
Closes #297 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Documentation (update in the documentation)

## Checklist:

- [x] I've read the [CONTRIBUTION](https://github.com/DLR-RM/stable-baselines3/blob/master/CONTRIBUTING.md) guide (**required**)
- [x] I have updated the changelog accordingly (**required**).
- [x] My change requires a change to the documentation.
- [ ] I have updated the tests accordingly (*required for a bug fix or a new feature*).
- [x] I have updated the documentation accordingly.
- [x] I have reformatted the code using `make format` (**required**)
- [x] I have checked the codestyle using `make check-codestyle` and `make lint` (**required**)
- [x] I have ensured `make pytest` and `make type` both pass. (**required**)

Note: we are using a maximum length of 127 characters per line

2022-10-12 12:31 UTC, richter43 commented
Hope the explanation is clear enough.

I added it below the Colab section given that it is an interactive programming environment, maybe it should've been placed somewhere else.

2022-10-12 15:29 UTC, qgallouedec requested changes

2022-10-12 15:29 UTC, qgallouedec commented on README.md
> +Modifying `sys.argv` is a possible way for passing arguments in an interactive computational environment (e.g: Jupyter Notebooks, IPython) without the need to launch a new Python process.
Answering to https://github.com/DLR-RM/rl-baselines3-zoo/issues/297#issuecomment-1276313591

Ok, then I would add some kind of disclaimer:

"The zoo is not meant to be used from an interactive session. But ..."

2022-10-13 15:33 UTC, closed without merging

2022-10-13 15:34 UTC, araffin commented
@richter43 I couldn't push edits to your branch as you use master (protected by default), so I pushed my changes to #301 .